on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test and build
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - name: Checkout code
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
      - name: Run linters
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          ./pre-commit

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion: [1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18]
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.goversion }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          go version
          make test
      - name: Build binary for inttest
        run: GO111MODULE=on make build-linux
      - name: Integration test
        run: make inttest

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build
        run: |
          go version
          export GO111MODULE=on
          make build-linux
          make build-windows
          make build-darwin
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: bin
          path: bin/
